version: "3.9"

services:
  
  db:
    image: postgres:15
    container_name: pg_cont
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: ./app
    container_name: django_cont
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  media_volume:
