version: "3.9"

services:
  
  db:
    image: postgres:15
    container_name: pg_cont
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    image: app_dock:latest
    container_name: django_cont
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    command: python manage.py collectstatic && python manage.py migrate && sh /run_uwsgi.sh
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  media_volume:
